import { WorkflowError } from '../errors.js';

export const TERMINAL_REVIEW_STATES = new Set([
  'CONVERTER_REPORT_READY',
  'RUNTIME_PARITY_PASSED',
  'RUNTIME_PARITY_PASSED_WITH_USER_DECLARED_ENVIRONMENT',
  'REVIEW_SUPERSEDED_BY_REFRESH',
]);

export const REVIEW_TRANSITIONS = Object.freeze({
  REVIEW_OPEN: ['ENVIRONMENT_PREFLIGHT', 'RUNTIME_NOT_TESTED', 'TARGET_EXTERNALLY_MODIFIED'],
  ENVIRONMENT_PREFLIGHT: ['RUNTIME_TESTING', 'RUNTIME_DIAGNOSTIC_TESTING', 'AWAITING_USER_BINDING', 'BLOCKED_ENVIRONMENT', 'TARGET_EXTERNALLY_MODIFIED'],
  AWAITING_USER_BINDING: ['ENVIRONMENT_PREFLIGHT', 'TARGET_EXTERNALLY_MODIFIED'],
  BLOCKED_ENVIRONMENT: ['ENVIRONMENT_PREFLIGHT', 'TARGET_EXTERNALLY_MODIFIED'],
  RUNTIME_TESTING: ['RUNTIME_PARITY_PASSED', 'RUNTIME_PARITY_PASSED_WITH_USER_DECLARED_ENVIRONMENT', 'MISMATCH_DETECTED', 'RUNTIME_NOT_TESTED', 'BLOCKED_PLATFORM_RUNTIME', 'TARGET_EXTERNALLY_MODIFIED'],
  RUNTIME_DIAGNOSTIC_TESTING: ['DIAGNOSTIC_RUNTIME_PASSED_WITH_ENVIRONMENT_RISK', 'MISMATCH_UNDER_ENVIRONMENT_RISK', 'DIAGNOSTIC_RUNTIME_INCONCLUSIVE_WITH_ENVIRONMENT_RISK', 'TARGET_EXTERNALLY_MODIFIED'],
  MISMATCH_UNDER_ENVIRONMENT_RISK: ['ENVIRONMENT_PREFLIGHT', 'RUNTIME_DIAGNOSTIC_TESTING', 'TARGET_EXTERNALLY_MODIFIED'],
  MISMATCH_DETECTED: ['DIAGNOSING', 'TARGET_EXTERNALLY_MODIFIED'],
  DIAGNOSING: ['CONVERTER_REPORT_READY', 'REPAIR_PROPOSED', 'TEST_OR_ENV_REPAIR', 'AUTO_REPAIR_STOPPED', 'BLOCKED_PLATFORM_RUNTIME', 'RUNTIME_REPAIR_EXHAUSTED', 'TARGET_EXTERNALLY_MODIFIED'],
  REPAIR_PROPOSED: ['LOCAL_VALIDATING', 'DIAGNOSING', 'TARGET_EXTERNALLY_MODIFIED'],
  TEST_OR_ENV_REPAIR: ['RUNTIME_TESTING', 'RUNTIME_DIAGNOSTIC_TESTING', 'TARGET_EXTERNALLY_MODIFIED'],
  AUTO_REPAIR_STOPPED: ['AWAITING_HUMAN_EVIDENCE', 'DIAGNOSING', 'TARGET_EXTERNALLY_MODIFIED'],
  AWAITING_HUMAN_EVIDENCE: ['DIAGNOSING', 'TARGET_EXTERNALLY_MODIFIED'],
  LOCAL_VALIDATING: ['READY_TO_UPDATE_TARGET', 'DIAGNOSING', 'TARGET_EXTERNALLY_MODIFIED'],
  READY_TO_UPDATE_TARGET: ['TARGET_UPDATED', 'TARGET_EXTERNALLY_MODIFIED', 'BLOCKED_PLATFORM_RUNTIME'],
  TARGET_UPDATED: ['RUNTIME_RETESTING', 'TARGET_EXTERNALLY_MODIFIED'],
  TARGET_EXTERNALLY_MODIFIED: ['LOCAL_VALIDATING'],
  RUNTIME_RETESTING: ['RUNTIME_PARITY_PASSED', 'RUNTIME_PARITY_PASSED_WITH_USER_DECLARED_ENVIRONMENT', 'MISMATCH_DETECTED', 'RUNTIME_NOT_TESTED', 'TARGET_UPDATED', 'BLOCKED_PLATFORM_RUNTIME', 'TARGET_EXTERNALLY_MODIFIED'],
  RUNTIME_REPAIR_EXHAUSTED: ['AWAITING_HUMAN_EVIDENCE', 'DIAGNOSING', 'TARGET_EXTERNALLY_MODIFIED'],
  BLOCKED_PLATFORM_RUNTIME: ['DIAGNOSING', 'RUNTIME_TESTING', 'RUNTIME_DIAGNOSTIC_TESTING', 'TARGET_UPDATED', 'AWAITING_HUMAN_EVIDENCE', 'TARGET_EXTERNALLY_MODIFIED'],
  RUNTIME_NOT_TESTED: ['ENVIRONMENT_PREFLIGHT', 'TARGET_EXTERNALLY_MODIFIED'],
  DIAGNOSTIC_RUNTIME_PASSED_WITH_ENVIRONMENT_RISK: ['ENVIRONMENT_PREFLIGHT', 'RUNTIME_DIAGNOSTIC_TESTING', 'TARGET_EXTERNALLY_MODIFIED'],
  DIAGNOSTIC_RUNTIME_INCONCLUSIVE_WITH_ENVIRONMENT_RISK: ['ENVIRONMENT_PREFLIGHT', 'RUNTIME_DIAGNOSTIC_TESTING', 'TARGET_EXTERNALLY_MODIFIED'],
});

export function assertReviewTransition(from, to) {
  if (TERMINAL_REVIEW_STATES.has(from)) {
    throw new WorkflowError('REVIEW_ALREADY_TERMINAL', `Cannot transition terminal review from ${from} to ${to}`);
  }
  const allowed = REVIEW_TRANSITIONS[from] || [];
  if (!allowed.includes(to)) {
    throw new WorkflowError(
      'INVALID_REVIEW_TRANSITION',
      `Cannot transition review from ${from} to ${to}`,
      { from, to, allowed },
    );
  }
}
