import { WorkflowError } from '../errors.js';

export const TERMINAL_STATES = new Set([
  'SUCCEEDED',
  'DIAGNOSTIC_COPY_CREATED',
  'DRY_RUN_SUCCEEDED',
  'SKIPPED_ALREADY_V5',
  'SKIPPED_OUT_OF_SCOPE',
  'VERSION_AMBIGUOUS',
  'UNSUPPORTED_V4_FORMAT',
  'AUTH_FAILED',
  'SOURCE_PERMISSION_DENIED',
  'TARGET_PERMISSION_DENIED',
  'PLATFORM_FAILED',
  'FAILED',
]);

export const TRANSITIONS = Object.freeze({
  RECEIVED: ['UPDATE_CHECKED', 'FAILED'],
  UPDATE_CHECKED: ['AUTHORIZED', 'AUTH_FAILED', 'FAILED'],
  AUTHORIZED: ['VERSION_CLASSIFIED', 'SOURCE_PERMISSION_DENIED', 'TARGET_PERMISSION_DENIED', 'FAILED'],
  VERSION_CLASSIFIED: [
    'SOURCE_LOADED',
    'SKIPPED_ALREADY_V5',
    'SKIPPED_OUT_OF_SCOPE',
    'VERSION_AMBIGUOUS',
    'UNSUPPORTED_V4_FORMAT',
    'FAILED',
  ],
  SOURCE_LOADED: ['CONVERTED', 'SOURCE_CHANGED', 'FAILED'],
  SOURCE_CHANGED: ['SOURCE_LOADED', 'FAILED'],
  CONVERTED: ['VALIDATED', 'FAILED'],
  VALIDATED: ['ISSUES_CLASSIFIED', 'NEEDS_REVIEW', 'FAILED'],
  ISSUES_CLASSIFIED: [
    'AI_REPAIR_REQUIRED',
    'BLOCKED_CONVERTER_DEFECT',
    'NEEDS_REVIEW',
    'READY_TO_SAVE',
    'DRY_RUN_SUCCEEDED',
    'FAILED',
  ],
  AI_REPAIR_REQUIRED: ['AI_REPAIRED', 'READY_TO_SAVE_DIAGNOSTIC_COPY', 'NEEDS_REVIEW', 'FAILED'],
  AI_REPAIRED: ['VALIDATED', 'NEEDS_REVIEW', 'FAILED'],
  BLOCKED_CONVERTER_DEFECT: ['READY_TO_SAVE_DIAGNOSTIC_COPY'],
  NEEDS_REVIEW: ['READY_TO_SAVE_DIAGNOSTIC_COPY'],
  READY_TO_SAVE: ['SOURCE_CHANGED', 'SAVE_AS_CREATED', 'SAVE_INCOMPLETE', 'TARGET_PERMISSION_DENIED', 'PLATFORM_FAILED'],
  READY_TO_SAVE_DIAGNOSTIC_COPY: ['SOURCE_CHANGED', 'SAVE_AS_CREATED', 'SAVE_INCOMPLETE', 'TARGET_PERMISSION_DENIED', 'PLATFORM_FAILED'],
  SAVE_AS_CREATED: ['FINAL_SAVED', 'SAVE_INCOMPLETE', 'PLATFORM_FAILED'],
  SAVE_INCOMPLETE: ['SAVE_AS_CREATED', 'FINAL_SAVED', 'POST_SAVE_VERIFIED', 'PLATFORM_FAILED'],
  FINAL_SAVED: ['POST_SAVE_VERIFIED', 'SAVE_INCOMPLETE', 'PLATFORM_FAILED'],
  POST_SAVE_VERIFIED: ['SUCCEEDED', 'DIAGNOSTIC_COPY_CREATED', 'SAVE_INCOMPLETE', 'PLATFORM_FAILED'],
});

export function assertTransition(from, to) {
  if (TERMINAL_STATES.has(from)) {
    throw new WorkflowError(
      'JOB_ALREADY_TERMINAL',
      `Cannot transition terminal job from ${from} to ${to}`,
    );
  }
  const allowed = TRANSITIONS[from] || [];
  if (!allowed.includes(to)) {
    throw new WorkflowError(
      'INVALID_JOB_TRANSITION',
      `Cannot transition job from ${from} to ${to}`,
      { from, to, allowed },
    );
  }
}
